[connections.snowflake]
account = "RPEUJNQ-JV45688"
user = "vikashrajan"
password = "Rajan321"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
